//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminKata {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class idiom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal idiom() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminKata.idiom", typeof(idiom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin.
        /// </summary>
        internal static string Administrador {
            get {
                return ResourceManager.GetString("Administrador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qualified competitors.
        /// </summary>
        internal static string Calificados {
            get {
                return ResourceManager.GetString("Calificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUK championship.
        /// </summary>
        internal static string Campeonato_AUK {
            get {
                return ResourceManager.GetString("Campeonato AUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tie case.
        /// </summary>
        internal static string Caso_empate {
            get {
                return ResourceManager.GetString("Caso empate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string Categoría {
            get {
                return ResourceManager.GetString("Categoría", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I.D..
        /// </summary>
        internal static string Cédula_de_identidad {
            get {
                return ResourceManager.GetString("Cédula de identidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell phone.
        /// </summary>
        internal static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tournament code.
        /// </summary>
        internal static string Código_de_torneo {
            get {
                return ResourceManager.GetString("Código de torneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competitors.
        /// </summary>
        internal static string Competidores {
            get {
                return ResourceManager.GetString("Competidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qualified Competitors.
        /// </summary>
        internal static string Competidores_Calificados {
            get {
                return ResourceManager.GetString("Competidores Calificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competitors entered.
        /// </summary>
        internal static string Competidores_Ingresados {
            get {
                return ResourceManager.GetString("Competidores Ingresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uruguayan Karate confederation.
        /// </summary>
        internal static string Confederación_Uruguaya_de_Karate {
            get {
                return ResourceManager.GetString("Confederación Uruguaya de Karate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Judges&apos; password.
        /// </summary>
        internal static string Contraseña_de_los_Jueces {
            get {
                return ResourceManager.GetString("Contraseña de los Jueces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create tournament.
        /// </summary>
        internal static string Crear_Torneo {
            get {
                return ResourceManager.GetString("Crear Torneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Judge&apos;s data.
        /// </summary>
        internal static string Datos_de_Jueces {
            get {
                return ResourceManager.GetString("Datos de Jueces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competitors&apos; data.
        /// </summary>
        internal static string Datos_de_los_Competidores {
            get {
                return ResourceManager.GetString("Datos de los Competidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disqualification.
        /// </summary>
        internal static string Descalificación {
            get {
                return ResourceManager.GetString("Descalificación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disqualify.
        /// </summary>
        internal static string Descalificar {
            get {
                return ResourceManager.GetString("Descalificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delate tournament.
        /// </summary>
        internal static string Eliminar_torneo {
            get {
                return ResourceManager.GetString("Eliminar torneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tie case.
        /// </summary>
        internal static string Empate {
            get {
                return ResourceManager.GetString("Empate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send score.
        /// </summary>
        internal static string Enviar_puntaje {
            get {
                return ResourceManager.GetString("Enviar puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send score to screen.
        /// </summary>
        internal static string Enviar_puntaje_a_pantalla {
            get {
                return ResourceManager.GetString("Enviar puntaje a pantalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a School.
        /// </summary>
        internal static string Escuela {
            get {
                return ResourceManager.GetString("Escuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        internal static string Femenino {
            get {
                return ResourceManager.GetString("Femenino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        internal static string Género {
            get {
                return ResourceManager.GetString("Género", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save data.
        /// </summary>
        internal static string Guardar_Datos {
            get {
                return ResourceManager.GetString("Guardar Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save kata.
        /// </summary>
        internal static string Guardar_Kata {
            get {
                return ResourceManager.GetString("Guardar Kata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save score.
        /// </summary>
        internal static string Guardar_puntaje {
            get {
                return ResourceManager.GetString("Guardar puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour.
        /// </summary>
        internal static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        internal static string Ingresar {
            get {
                return ResourceManager.GetString("Ingresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Judge.
        /// </summary>
        internal static string Juez {
            get {
                return ResourceManager.GetString("Juez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competitors&apos; Kata.
        /// </summary>
        internal static string Kata_Competidores {
            get {
                return ResourceManager.GetString("Kata Competidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Place.
        /// </summary>
        internal static string Lugar {
            get {
                return ResourceManager.GetString("Lugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        internal static string Masculino {
            get {
                return ResourceManager.GetString("Masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main menu.
        /// </summary>
        internal static string Menú_Principal {
            get {
                return ResourceManager.GetString("Menú Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show on screen.
        /// </summary>
        internal static string Mostrar_pantalla {
            get {
                return ResourceManager.GetString("Mostrar pantalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        internal static string Nacimiento {
            get {
                return ResourceManager.GetString("Nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Didn&apos;t grate at doing the kata.
        /// </summary>
        internal static string No_realizó_el_saludo_al_iniciar_el_Kata {
            get {
                return ResourceManager.GetString("No realizó el saludo al iniciar el Kata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Did not show up.
        /// </summary>
        internal static string No_se_presentó {
            get {
                return ResourceManager.GetString("No se presentó", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Judge number.
        /// </summary>
        internal static string Número_de_juez {
            get {
                return ResourceManager.GetString("Número de juez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Judge Numer.
        /// </summary>
        internal static string Número_Juez {
            get {
                return ResourceManager.GetString("Número Juez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        internal static string Olvidé_mi_contraseña {
            get {
                return ResourceManager.GetString("Olvidé mi contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string Otro {
            get {
                return ResourceManager.GetString("Otro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Qualified screen.
        /// </summary>
        internal static string Pantalla_Calificados {
            get {
                return ResourceManager.GetString("Pantalla Calificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participants screen.
        /// </summary>
        internal static string Pantalla_Participantes {
            get {
                return ResourceManager.GetString("Pantalla Participantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main screen.
        /// </summary>
        internal static string Pantalla_Principal {
            get {
                return ResourceManager.GetString("Pantalla Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score screen.
        /// </summary>
        internal static string Pantalla_Puntajes {
            get {
                return ResourceManager.GetString("Pantalla Puntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter the information requested below to receive the password.
        /// </summary>
        internal static string Por_favor__ingrese_los_datos_pedidos_a_continuación_para_recibir_la_contraseña {
            get {
                return ResourceManager.GetString("Por favor, ingrese los datos pedidos a continuación para recibir la contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Professor in charge.
        /// </summary>
        internal static string Profesor_a_cargo {
            get {
                return ResourceManager.GetString("Profesor a cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score.
        /// </summary>
        internal static string Puntajes {
            get {
                return ResourceManager.GetString("Puntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score of.
        /// </summary>
        internal static string Puntuación_de {
            get {
                return ResourceManager.GetString("Puntuación de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Receive password.
        /// </summary>
        internal static string Recibir_contraseña {
            get {
                return ResourceManager.GetString("Recibir contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        internal static string Recuperar_contraseña {
            get {
                return ResourceManager.GetString("Recuperar contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tournament registration.
        /// </summary>
        internal static string Registro_de_torneo {
            get {
                return ResourceManager.GetString("Registro de torneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Was injured while performing the kata.
        /// </summary>
        internal static string Se_lesionó_al_realizar_el_kata {
            get {
                return ResourceManager.GetString("Se lesionó al realizar el kata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medical Society.
        /// </summary>
        internal static string Sociedad_Médica {
            get {
                return ResourceManager.GetString("Sociedad Médica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw.
        /// </summary>
        internal static string Sortear {
            get {
                return ResourceManager.GetString("Sortear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw Competitors.
        /// </summary>
        internal static string Sortear_competidores {
            get {
                return ResourceManager.GetString("Sortear competidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tournament.
        /// </summary>
        internal static string Torneo {
            get {
                return ResourceManager.GetString("Torneo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existing tournaments.
        /// </summary>
        internal static string Torneos_Existentes {
            get {
                return ResourceManager.GetString("Torneos Existentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score validation.
        /// </summary>
        internal static string Validación_de_puntajes {
            get {
                return ResourceManager.GetString("Validación de puntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score validation.
        /// </summary>
        internal static string Validar_puntajes {
            get {
                return ResourceManager.GetString("Validar puntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Health Card Expiration.
        /// </summary>
        internal static string Vencimiento_Carnet_de_Salud {
            get {
                return ResourceManager.GetString("Vencimiento Carnet de Salud", resourceCulture);
            }
        }
    }
}
